# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Nginx Deployment inside 'dev' namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev   # 👈 deploy in 'dev' namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
# Service to expose Nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev   # 👈 service also in 'dev'
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
