apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: webapp
    version: green
spec:
  replicas: 1   # 25% of traffic
  selector:
    matchLabels:
      app: webapp
      version: green
  template:
    metadata:
      labels:
        app: webapp
        version: green
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80
