apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: webapp
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: blue
  template:
    metadata:
      labels:
        app: webapp
        version: blue
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
