apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
    version: blue   # <- change to green to switch traffic
  type: NodePort
  ports:
    - port: 8080        # Service port inside cluster
      targetPort: 80    # Container port
      nodePort: 30080   # NodePort for external access
